// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

abstract class AppRs {
  String hello({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kHelloConstMeta;

  Future<String> helloAsync({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kHelloAsyncConstMeta;

  Future<bool> appLoad({required Config config, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAppLoadConstMeta;

  Future<void> appRecover(
      {required Config config, required String seedPhrase, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAppRecoverConstMeta;

  Future<void> appSignup({required Config config, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAppSignupConstMeta;

  Config regtestStaticMethodConfig({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRegtestStaticMethodConfigConstMeta;

  Future<void> testMethodMethodAppHandle(
      {required AppHandle that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kTestMethodMethodAppHandleConstMeta;

  Future<AppHandle?> loadStaticMethodAppHandle(
      {required Config config, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kLoadStaticMethodAppHandleConstMeta;

  Future<AppHandle> recoverStaticMethodAppHandle(
      {required Config config, required String seedPhrase, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRecoverStaticMethodAppHandleConstMeta;

  Future<AppHandle> signupStaticMethodAppHandle(
      {required Config config, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSignupStaticMethodAppHandleConstMeta;
}

/// The `AppHandle` is a Dart representation of a current [`App`] instance.
class AppHandle {
  final AppRs bridge;
  final int instanceId;

  AppHandle({
    required this.bridge,
    required this.instanceId,
  });

  Future<void> testMethod({dynamic hint}) => bridge.testMethodMethodAppHandle(
        that: this,
      );

  static Future<AppHandle?> load(
          {required AppRs bridge, required Config config, dynamic hint}) =>
      bridge.loadStaticMethodAppHandle(config: config, hint: hint);

  static Future<AppHandle> recover(
          {required AppRs bridge,
          required Config config,
          required String seedPhrase,
          dynamic hint}) =>
      bridge.recoverStaticMethodAppHandle(
          config: config, seedPhrase: seedPhrase, hint: hint);

  static Future<AppHandle> signup(
          {required AppRs bridge, required Config config, dynamic hint}) =>
      bridge.signupStaticMethodAppHandle(config: config, hint: hint);
}

enum BuildVariant {
  Production,
  Staging,
  Development,
}

class Config {
  final AppRs bridge;
  final BuildVariant buildVariant;
  final Network network;

  Config({
    required this.bridge,
    required this.buildVariant,
    required this.network,
  });

  static Config regtest({required AppRs bridge, dynamic hint}) =>
      bridge.regtestStaticMethodConfig(hint: hint);
}

enum Network {
  Bitcoin,
  Testnet,
  Regtest,
}
