[package]
name = "app-rs-codegen"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
argh.workspace = true
flutter_rust_bridge_codegen.workspace = true
