max_width = 80
use_field_init_shorthand = true
merge_derives = false

# Requires nightly
wrap_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_arm_blocks = false
