[package]
name = "sdk-core"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

# --- LEXE --- #

common = { path = "../common" }

# --- WORKSPACE --- #

anyhow.workspace = true
semver.workspace = true
serde.workspace = true
