[package]
name = "sgxs-sign"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

# --- LEXE --- #

byte-array.path = "../byte-array"
common.path = "../common"
hex.path = "../hex"
sha256.path = "../sha256"

# --- WORKSPACE --- #

anyhow.workspace = true
rsa.workspace = true
sgxs.workspace = true
