//! The native Rust code for the Lexe mobile app.

// Enforce disallowed methods clippy lint
#![deny(clippy::disallowed_methods)]
// Allow e.g. `CHANNEL_MANAGER` in generics to clearly distinguish between
// concrete and generic types
#![allow(non_camel_case_types)]

/// The high-level flutter/rust interface.
pub mod bindings;

/// The flutter/rust ffi bindings generated by `flutter_rust_bridge`.
pub mod bindings_generated;
