//! The native Rust code for the Lexe mobile app.

// Enforce disallowed methods clippy lint
#![deny(clippy::disallowed_methods)]
// Allow e.g. `CHANNEL_MANAGER` in generics to clearly distinguish between
// concrete and generic types
#![allow(non_camel_case_types)]
// Allow this in generated code
#![allow(clippy::not_unsafe_ptr_arg_deref)]

/// The high-level flutter/rust interface.
pub mod bindings;

/// The flutter/rust ffi bindings generated by `flutter_rust_bridge`.
pub mod bindings_generated;

/// Securely store and retrieve user credentials to and from each platform's
/// standard secret storage.
pub mod secret_store;

/// The top-level App state
pub mod app;
