name: app_embed_git_rev
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
