[package]
name = "lexe-uri"
version = "0.1.26"
license = "MIT"
description = "Minimal URI parsing and encoding"
documentation = "https://docs.rs/lexe-uri"
authors = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
publish = true

[lints]
workspace = true

# Default config for testing in SGX
[package.metadata.fortanix-sgx]

[dependencies]
percent-encoding = { workspace = true }

[dev-dependencies]
proptest = { workspace = true, features = ["alloc"] }
