[package]
name = "sha256"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

# --- LEXE --- #

const-utils.path = "../const-utils"
hex.path = "../hex"

# --- WORKSPACE --- #

ref-cast.workspace = true
ring.workspace = true
secp256k1.workspace = true
