name: app_lints
description: Custom lint rules shared across Lexe Dart packages.
publish_to: none
version: 0.1.0

environment:
  sdk: 3.8.0

dependencies:
  analyzer: ^8.1.1
  custom_lint_builder: ^0.8.1

dev_dependencies:
  custom_lint: ^0.8.1
  lints: ^6.0.0
  test: ^1.26.3
