name: app_lints
description: Custom lint rules shared across Lexe Dart packages.
publish_to: none
version: 0.1.0

environment:
  sdk: 3.8.0

dependencies:
  analyzer: ^8.1.1
  custom_lint_builder: ^0.8.1

dev_dependencies:
  analyzer_plugin: 0.13.7 # unpin after updating to dart sdk 3.9.0+
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test: ^1.26.3
