[package]
name = "sgx-test"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# --- LEXE --- #

common.path = "../common"
hex.path = "../hex"
lexe-api.path = "../lexe-api"

[package.metadata.fortanix-sgx]
# When true, return panics w/ backtraces to the host via the shared "debug
# buffer". We need this to debug panics in prod. rust-std also currently saves
# some registers so a debugger can reconstruct the stack.
# NOTE: this is not the same as the SGX platform DEBUG mode, which disables all
# memory protections.
# TODO(phlip9): patch rust-std so it always saves panics w/ backtraces but only
# dumps registers if `debug = true`.
debug = true
# Heap size in bytes. Default: 0x200_0000.
heap-size = 0x20_0000
# SSA frame size (in pages) for each thread. Default: 1.
# You normally don't need to change the SSA frame size.
ssaframesize = 1
# Stack size (in bytes) for each thread. Default: 0x2_0000.
stack-size = 0x2_0000
# The max number of threads we can spawn concurrently inside the SGX enclave.
threads = 1
