// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

//
// From: `dart_preamble` in `app-rs-codegen/src/lib.rs`
// ignore_for_file: invalid_internal_annotation, always_use_package_imports, directives_ordering, prefer_const_constructors, sort_unnamed_constructors_first
//

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'db.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// In-memory app state.
class AppData {
  /// AppDb schema version.
  final SchemaVersion schema;

  /// User's preferred Offer. Based on the user's human Bitcoin address.
  final String? offer;

  /// User's username to receive BIP353 and lnurl payments.
  final String? username;

  const AppData({required this.schema, this.offer, this.username});

  @override
  int get hashCode => schema.hashCode ^ offer.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppData &&
          runtimeType == other.runtimeType &&
          schema == other.schema &&
          offer == other.offer &&
          username == other.username;
}
