// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

//
// From: `dart_preamble` in `app-rs-codegen/src/lib.rs`
// ignore_for_file: invalid_internal_annotation, always_use_package_imports, directives_ordering, prefer_const_constructors, sort_unnamed_constructors_first
//

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GDriveSignupCredentials {
  /// The user's backup password, used to encrypt their `RootSeed` backup
  /// on Google Drive.
  final String backupPassword;

  /// The google auth code passed to the node enclave during provisioning.
  final String googleAuthCode;

  const GDriveSignupCredentials({
    required this.backupPassword,
    required this.googleAuthCode,
  });

  @override
  int get hashCode => backupPassword.hashCode ^ googleAuthCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GDriveSignupCredentials &&
          runtimeType == other.runtimeType &&
          backupPassword == other.backupPassword &&
          googleAuthCode == other.googleAuthCode;
}
