[package]
name = "run-sgx"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
# --- LEXE --- #

sgx-toml = { path = "../sgx-toml" }

# --- WORKSPACE --- #

anyhow.workspace = true
argh.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["net"] }

# --- CRATE-SPECIFIC --- #

# Efficiently find newline byte in byte array
memchr = "2"
# For symbolizing backtrace frames from the enclave
object = { version = "0.30", default-features = false, features = ["read_core", "compression", "elf"] }
# For demangling backtrace symbols into human-readable format
rustc-demangle = "0.1"

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.dependencies]
common = { path = "../common" }
sgxs-sign = { path = "../sgxs-sign" }

aesm-client.workspace = true
enclave-runner.workspace = true
sgx-isa.workspace = true
sgxs-loaders.workspace = true
