[package]
name = "run-sgx"
version = "0.1.0"
authors = [
    "Max Fang <protonmail.com@maxfa.ng>",
    "Philip Hayes <philiphayes9@gmail.com>"
]
license = "PolyForm Noncommercial License 1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Ad hoc error definition, easy error propagation, error chains
anyhow = "1"
# Derive-based command line argument parsing
argh = "0.1"
# Used to serialize / deserialize enclave config from Cargo.toml
serde = { version = "1", features = ["derive"] }
toml = "0.5"

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.dependencies]
# --- PATCHED DEPENDENCIES --- #
# - Be sure to use the specific patched versions.
# - See the workspace Cargo.toml for patch declarations.
# - The versions for transitive dependencies (such as hyper, mio, ring, etc) are
#   declared in `common`'s Cargo.toml and propagated to other crates by
#   workspace-level dependency resolution.

# A client for the Intel AESM service. Used in the attestation process to get quoted.
aesm-client = { version = "=0.5.4", default-features = false, features = ["sgxs"] }
enclave-runner = { version = "=0.5.1", default-features = false, features = ["crypto-openssl"] }
# The base SGX types and platform intrinsics (for sealing, reports, etc...)
sgx-isa = "=0.4.0"
sgxs-loaders = "=0.3.3"
tokio = { version = "=1.15.0", default-features = false, features = [
    "net"
] }
