[package]
name = "run-sgx"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
# --- LEXE --- #

sgx-toml.path = "../sgx-toml"

# --- WORKSPACE --- #

anyhow.workspace = true
argh.workspace = true
object.workspace = true
rustc-demangle.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["net"] }

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.dependencies]
common.path = "../common"
sgxs-sign.path = "../sgxs-sign"

aesm-client = { workspace = true, features = ["sgxs"] }
enclave-runner.workspace = true
sgx-isa.workspace = true
sgxs-loaders.workspace = true
