[package]
name = "lexe-ln"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
# Explicitly specify that no features should be enabled by default.
default = []
# Enables various test hooks and utilities. Should be disabled in staging/prod.
test-utils = ["common/test-utils"]

[dependencies]

# --- LEXE --- #

common = { path = "../common" }

# --- BITCOIN --- #

bitcoin.workspace = true
bitcoin-bech32.workspace = true
bitcoin_hashes.workspace = true
base64.workspace = true
# Descriptor-based Bitcoin wallet library
bdk = { version = "0.27", default-features = false, features = ["async-interface", "use-esplora-async"] }
# Async Esplora client
esplora-client = { version = "0.4", default-features = false, features = ["async"] }

# --- LIGHTNING --- #

lightning.workspace = true
lightning-invoice.workspace = true
lightning-net-tokio.workspace = true
lightning-transaction-sync.workspace = true

# --- WORKSPACE --- #

anyhow.workspace = true
async-trait.workspace = true
cfg-if.workspace = true
futures.workspace = true
rust_decimal.workspace = true
secrecy.workspace = true
semver.workspace = true
serde.workspace = true
serde_with = { workspace = true, features = ["alloc", "hex"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "sync",
    "time"
] }
tracing.workspace = true
tracing-core.workspace = true
tracing-subscriber = { workspace = true, features = [
    # Enable colored log outputs
    "ansi",
    "fmt",
    "registry",
    "std",
    "tracing-log",
] }

[dev-dependencies]
common = { path = "../common", features = ["test-utils"] }

proptest = { workspace = true, features = ["alloc"] }
proptest-derive.workspace = true
# Enable test-util feature in tests
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "rt",
    "sync",
    "test-util",
    "time"
] }
# Utilities for testing futures
tokio-test = "0.4"
