[package]
name = "lexe-ln"
version = "0.1.0"
authors = [
    "Max Fang <protonmail.com@maxfa.ng>",
    "Philip Hayes <philiphayes9@gmail.com>"
]
license = "PolyForm Noncommercial License 1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# --- LEXE --- #

# Shared code
common = { path = "../common" }

# --- BITCOIN --- #

bitcoin = { version = "0.28.1", features = ["use-serde"] }
bitcoin-bech32 = "0.12"
# bech32 = "0.8"
base64 = "0.13.0"

# --- LIGHTNING --- #

lightning = { version = "0.0.110", features = ["max_level_trace"] }
lightning-block-sync = { version = "0.0.110", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.18" }
lightning-net-tokio = { version = "0.0.110" }

# lightning = { git = "https://github.com/lexe-tech/rust-lightning", features = # ["max_level_trace"], branch = "main" }
# lightning-block-sync = { git = "https://github.com/lexe-tech/rust-lightning", # features = [ "rpc-client" ], branch = "main" }
# lightning-invoice = { git = "https://github.com/lexe-tech/rust-lightning", # branch = "main" }
# lightning-net-tokio = { git = "https://github.com/lexe-tech/rust-lightning", # branch = "main" }

# For debugging and testing patches during local development
# lightning = { path = "../../ldk/lightning", features = ["max_level_trace"]}
# lightning-block-sync = { path = "../../ldk/lightning-block-sync", features = [ "rpc-client" ] }
# lightning-invoice = { path = "../../ldk/lightning-invoice" }
# lightning-net-tokio = { path = "../../ldk/lightning-net-tokio" }

# --- GENERAL --- #

# Ad hoc error definition, easy error propagation, error chains
anyhow = "1"
# A wrapper type for carefully handling secrets
secrecy = "0.8"
