[package]
name = "lexe-ln"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []
# Enables various test hooks and utilities. Should be disabled in staging/prod.
test-utils = ["common/test-utils"]

[dependencies]

# --- LEXE --- #

common = { path = "../common" }

# --- WORKSPACE --- #

anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
base64.workspace = true
bech32.workspace = true
bitcoin.workspace = true
bitcoin-bech32.workspace = true
bitcoin_hashes.workspace = true
cfg-if.workspace = true
futures.workspace = true
lightning.workspace = true
lightning-invoice.workspace = true
lightning-net-tokio.workspace = true
lightning-transaction-sync.workspace = true
rand.workspace = true
# TODO(max): Remove once esplora-client no longer needs it
reqwest11 = { workspace = true, features = ["rustls-tls-manual-roots"] }
rust_decimal.workspace = true
secrecy.workspace = true
semver.workspace = true
serde.workspace = true
serde_with = { workspace = true, features = ["alloc", "hex"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "sync",
    "time"
] }
tracing.workspace = true
tracing-core.workspace = true
tracing-subscriber = { workspace = true, features = [
    # Enable colored log outputs
    "ansi",
    "fmt",
    "registry",
    "std",
    "tracing-log",
] }

# --- CRATE-SPECIFIC --- #

# BDK suite of libraries
bdk_wallet = { version = "=1.0.0-beta.5", default-features = false, features = ["std"] }
bdk_chain = { version = "0.20", default-features = false, features = ["std"] }
bdk_esplora = { version = "0.19", default-features = false, features = ["std", "async"] }

# Async Esplora client
esplora-client = { version = "0.10", default-features = false, features = ["async", "tokio"] }
# Pieter Wuille's simpler alternative to Bitcoin Script
# The version should match that used by BDK.
miniscript = { version = "12", features = ["std"] }
# TODO(max): Remove once esplora-client no longer needs it...
rustls21 = { package = "rustls", version = "0.21", default-features = false }
# Mozilla's set of trusted webpki root certificates hard-coded into a const
webpki-roots = "0.26"

[dev-dependencies]
common = { path = "../common", features = ["test-utils"] }

proptest = { workspace = true, features = ["alloc"] }
proptest-derive.workspace = true
strum.workspace = true
# Enable test-util feature in tests
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "rt",
    "sync",
    "test-util",
    "time"
] }
# Utilities for testing futures
tokio-test = "0.4"
