// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

//
// From: `dart_preamble` in `app-rs-codegen/src/lib.rs`
// ignore_for_file: invalid_internal_annotation, always_use_package_imports, directives_ordering, prefer_const_constructors, sort_unnamed_constructors_first
//

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'app.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'types.dart';
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_cid_and_response`, `from_id_and_response`, `from_id_and_response`, `validate_note`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`

/// The user's active human Bitcoin address, plus the per-user `updatable`
/// policy flag (whether the user can claim a different custom username now).
///
/// The FFI-flattened form of [`ActiveHumanBitcoinAddressRs`].
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class ActiveHumanBitcoinAddress with _$ActiveHumanBitcoinAddress {
  const factory ActiveHumanBitcoinAddress({
    required Username username,
    required Offer offer,
    required int updatedAt,
    int? expiresAt,
    required bool isGenerated,
    required bool updatable,
  }) = _ActiveHumanBitcoinAddress;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class Balance with _$Balance {
  const factory Balance({
    required int totalSats,
    required int onchainSats,
    required int lightningSats,
    required int lightningUsableSats,
    required int lightningMaxSendableSats,
  }) = _Balance;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CloseChannelPreflightResponse
    with _$CloseChannelPreflightResponse {
  const factory CloseChannelPreflightResponse({required int feeEstimateSats}) =
      _CloseChannelPreflightResponse;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CloseChannelRequest with _$CloseChannelRequest {
  const factory CloseChannelRequest({required String channelId}) =
      _CloseChannelRequest;
}

/// See `lexe_common::api::revocable_clients::models::CreateRevocableClientRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CreateClientRequest with _$CreateClientRequest {
  const factory CreateClientRequest({String? label, required LexeScope scope}) =
      _CreateClientRequest;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CreateClientResponse with _$CreateClientResponse {
  const factory CreateClientResponse({
    required RevocableClient client,
    required String credentials,
  }) = _CreateClientResponse;
}

/// See `lexe_api::command::CreateInvoiceRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CreateInvoiceRequest with _$CreateInvoiceRequest {
  const factory CreateInvoiceRequest({
    required int expirySecs,
    int? amountSats,
    String? description,
    String? personalNote,
    required PaymentKind kind,
  }) = _CreateInvoiceRequest;
}

/// See `lexe_api::command::CreateInvoiceResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CreateInvoiceResponse with _$CreateInvoiceResponse {
  const factory CreateInvoiceResponse({required Invoice invoice}) =
      _CreateInvoiceResponse;
}

/// See `lexe_api::command::CreateOfferRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CreateOfferRequest with _$CreateOfferRequest {
  const factory CreateOfferRequest({
    int? expirySecs,
    int? minAmountSats,
    String? description,
    String? issuer,
  }) = _CreateOfferRequest;
}

/// See `lexe_api::command::CreateOfferResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class CreateOfferResponse with _$CreateOfferResponse {
  const factory CreateOfferResponse({required Offer offer}) =
      _CreateOfferResponse;
}

/// See `lexe_api::command::FeeEstimate`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class FeeEstimate with _$FeeEstimate {
  const factory FeeEstimate({required int amountSats}) = _FeeEstimate;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class FiatRate with _$FiatRate {
  const factory FiatRate({required String fiat, required double rate}) =
      _FiatRate;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class FiatRates with _$FiatRates {
  const factory FiatRates({
    required int timestampMs,
    required List<FiatRate> rates,
  }) = _FiatRates;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class ListChannelsResponse with _$ListChannelsResponse {
  const factory ListChannelsResponse({
    required List<LxChannelDetails> channels,
  }) = _ListChannelsResponse;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class NodeInfo with _$NodeInfo {
  const factory NodeInfo({
    required String nodePk,
    required String version,
    required String measurement,
    required Balance balance,
  }) = _NodeInfo;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class OpenChannelPreflightRequest with _$OpenChannelPreflightRequest {
  const factory OpenChannelPreflightRequest({required int valueSats}) =
      _OpenChannelPreflightRequest;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class OpenChannelPreflightResponse with _$OpenChannelPreflightResponse {
  const factory OpenChannelPreflightResponse({required int feeEstimateSats}) =
      _OpenChannelPreflightResponse;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class OpenChannelRequest with _$OpenChannelRequest {
  const factory OpenChannelRequest({
    required UserChannelId userChannelId,
    required int valueSats,
  }) = _OpenChannelRequest;
}

/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class OpenChannelResponse with _$OpenChannelResponse {
  const factory OpenChannelResponse({required String channelId}) =
      _OpenChannelResponse;
}

/// See `lexe_api::command::PayInvoicePreflightRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayInvoicePreflightRequest with _$PayInvoicePreflightRequest {
  const factory PayInvoicePreflightRequest({
    required String invoice,
    int? fallbackAmountSats,
    required PaymentKind kind,
  }) = _PayInvoicePreflightRequest;
}

/// See `lexe_api::command::PayInvoicePreflightResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayInvoicePreflightResponse with _$PayInvoicePreflightResponse {
  const factory PayInvoicePreflightResponse({
    required int amountSats,
    required int feesSats,
  }) = _PayInvoicePreflightResponse;
}

/// Mirrors the `lexe_api::command::PayInvoiceRequest` type.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayInvoiceRequest with _$PayInvoiceRequest {
  const factory PayInvoiceRequest({
    required String invoice,
    int? fallbackAmountSats,
    String? message,
    String? personalNote,
    required PaymentKind kind,
  }) = _PayInvoiceRequest;
}

/// Mirrors `lexe_api::command::PayInvoiceResponse` the type, but enriches
/// the response so we get the full `PaymentCreatedIndex`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayInvoiceResponse with _$PayInvoiceResponse {
  const factory PayInvoiceResponse({required PaymentCreatedIndex index}) =
      _PayInvoiceResponse;
}

/// See `lexe_api::command::PayOfferPreflightRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOfferPreflightRequest with _$PayOfferPreflightRequest {
  const factory PayOfferPreflightRequest({
    required ClientPaymentId cid,
    required String offer,
    required int amountSats,
  }) = _PayOfferPreflightRequest;
}

/// See `lexe_api::command::PayOfferPreflightResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOfferPreflightResponse with _$PayOfferPreflightResponse {
  const factory PayOfferPreflightResponse({
    required int amountSats,
    required int feesSats,
  }) = _PayOfferPreflightResponse;
}

/// See `lexe_api::command::PayOfferResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOfferRequest with _$PayOfferRequest {
  const factory PayOfferRequest({
    required ClientPaymentId cid,
    required String offer,
    required int amountSats,
    String? message,
    String? personalNote,
    required PaymentKind kind,
  }) = _PayOfferRequest;
}

/// See `lexe_api::command::PayOfferResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOfferResponse with _$PayOfferResponse {
  const factory PayOfferResponse({required PaymentCreatedIndex index}) =
      _PayOfferResponse;
}

/// See `lexe_api::command::PayOnchainPreflightRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOnchainPreflightRequest with _$PayOnchainPreflightRequest {
  const factory PayOnchainPreflightRequest({
    required String address,
    required int amountSats,
  }) = _PayOnchainPreflightRequest;
}

/// See `lexe_api::command::PayOnchainPreflightResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOnchainPreflightResponse with _$PayOnchainPreflightResponse {
  const factory PayOnchainPreflightResponse({
    FeeEstimate? high,
    required FeeEstimate normal,
    required FeeEstimate background,
  }) = _PayOnchainPreflightResponse;
}

/// See `lexe_api::command::PayOnchainRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOnchainRequest with _$PayOnchainRequest {
  const factory PayOnchainRequest({
    required ClientPaymentId cid,
    required String address,
    required int amountSats,
    required ConfirmationPriority priority,
    String? personalNote,
  }) = _PayOnchainRequest;
}

/// See `lexe_api::command::PayOnchainResponse`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class PayOnchainResponse with _$PayOnchainResponse {
  const factory PayOnchainResponse({
    required PaymentCreatedIndex index,
    required String txid,
  }) = _PayOnchainResponse;
}

/// See `lexe_common::api::revocable_clients::models::UpdateClientRequest`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class UpdateClientRequest with _$UpdateClientRequest {
  const factory UpdateClientRequest({required String pubkey, bool? isRevoked}) =
      _UpdateClientRequest;
}

/// See `lexe_common::api::user::UpdatePersonalNote`.
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class UpdatePersonalNote with _$UpdatePersonalNote {
  const factory UpdatePersonalNote({
    required PaymentCreatedIndex index,
    String? personalNote,
  }) = _UpdatePersonalNote;
}

/// See [`WithdrawLnurlRequestRs`].
///
/// flutter_rust_bridge:dart_metadata=("freezed")
@freezed
sealed class WithdrawLnurlRequest with _$WithdrawLnurlRequest {
  const factory WithdrawLnurlRequest({
    required LnurlWithdrawRequest withdrawRequest,
    required int amountMsat,
    String? description,
    String? personalNote,
  }) = _WithdrawLnurlRequest;
}
