// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

//
// From: `dart_preamble` in `app-rs-codegen/src/lib.rs`
// ignore_for_file: invalid_internal_annotation, always_use_package_imports, directives_ordering, prefer_const_constructors, sort_unnamed_constructors_first
//

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `try_from`, `try_from`, `try_from`, `try_from`

// Rust type: RustOpaqueNom<WritebackDbRs < AppDataRs >>
abstract class WritebackDbRsAppDataRs implements RustOpaqueInterface {}

class AppData {
  final HumanBitcoinAddress? humanBitcoinAddress;

  const AppData({this.humanBitcoinAddress});

  @override
  int get hashCode => humanBitcoinAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppData &&
          runtimeType == other.runtimeType &&
          humanBitcoinAddress == other.humanBitcoinAddress;
}

class AppDataDb {
  final WritebackDbRsAppDataRs inner;

  const AppDataDb({required this.inner});

  /// Read all data from the db.
  ///
  /// flutter_rust_bridge:sync
  AppData read() => AppRs.instance.api.crateFfiAppDataAppDataDbRead(that: this);

  /// Reset all data to their defaults.
  ///
  /// flutter_rust_bridge:sync
  void reset() => AppRs.instance.api.crateFfiAppDataAppDataDbReset(that: this);

  /// Update the in-memory db by merging in any non-null fields in
  /// `update`. The db will be persisted asynchronously, outside of this
  /// call.
  ///
  /// flutter_rust_bridge:sync
  void update({required AppData update}) => AppRs.instance.api
      .crateFfiAppDataAppDataDbUpdate(that: this, update: update);

  @override
  int get hashCode => inner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppDataDb &&
          runtimeType == other.runtimeType &&
          inner == other.inner;
}
