// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

//
// From: `dart_preamble` in `app-rs-codegen/src/lib.rs`
// ignore_for_file: invalid_internal_annotation, always_use_package_imports, directives_ordering, prefer_const_constructors, sort_unnamed_constructors_first
//

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Delete the local persisted `SecretStore` and `RootSeed`.
///
/// WARNING: you will need a backup recovery to use the account afterwards.
///
/// flutter_rust_bridge:sync
void deleteSecretStore({required Config config}) =>
    AppRs.instance.api.crateFfiDebugDeleteSecretStore(config: config);

/// Delete the local latest_release file.
///
/// flutter_rust_bridge:sync
void deleteLatestProvisioned({required Config config}) =>
    AppRs.instance.api.crateFfiDebugDeleteLatestProvisioned(config: config);

/// Unconditionally panic (for testing).
Future<void> unconditionalPanic() =>
    AppRs.instance.api.crateFfiDebugUnconditionalPanic();

/// Unconditionally return Err (for testing).
Future<void> unconditionalError() =>
    AppRs.instance.api.crateFfiDebugUnconditionalError();
